# Fichier : docker-compose.yml (mis à jour)

version: '3.8'

services:
  # NOUVEAU: Service de base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: rp_chat_db
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpassword
      POSTGRES_DB: chatdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql # Script d'initialisation
    ports:
      - "5432:5432" # Expose le port pour un débogage facile
    restart: on-failure

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: on-failure

  vllm:
    build:
      context: .
      dockerfile: vllm.Dockerfile
    runtime: nvidia
    volumes:
      - /scratch/hf_cache:/root/.cache/huggingface/hub
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command:
      - --host
      - 0.0.0.0
      - --model
      - huihui-ai/qwen2.5-32B-Instruct-abliterated
      - --max-model-len
      - '4096'
      - --gpu-memory-utilization
      - '0.90'
    ports:
      - "8000:8000"
    restart: on-failure

  backend:
    build:
      context: ./backend
    depends_on:
      - vllm
      - qdrant
      - postgres # On ajoute la dépendance à la BDD
    ports:
      - "8001:8001"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env
    # Les variables d'environnement sont maintenant définies dans le .env
    # Assurez-vous que votre .env contient les lignes suivantes
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_BACKEND_API_URL=http://backend:8001/api/v1 # URL de base de l'API
    restart: on-failure

volumes:
  postgres_data: # Volume pour la persistance des données de la BDD